spring.profiles.active=local

server.servlet.contextPath=/spring-neo4j-demo

spring.data.neo4j.uri=bolt://${DB_HOST:localhost}:${DB_PORT}
spring.data.neo4j.username=${DB_USERNAME}
spring.data.neo4j.password=${DB_PASSWORD}

logging.level.org.springframework.data.neo4j=DEBUG