database.host=localhost
database.port=7687
database.name=neo4j
database.username=neo4j
database.password=${DB_PASSWORD}

database.ssl.enabled=true
database.ssl.cert.path=${SSL_CERT_PATH}

logging.level.org.springframework.data.neo4j=DEBUG